{% set name = "asdf-unit-schemas" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asdf_unit_schemas-{{ version }}.tar.gz
  sha256: d995c45b5531ef1fe2e0525db30c7fc8b36df9447116ee067ce4461eea7e4440

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - asdf_unit_schemas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/asdf-unit-schemas/
  summary: ASDF schemas for units
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - braingram
    - WilliamJamieson
